DBZ-5551: Handle Vstream Connection reset
When there is a connection reset on Vitess side (e.g. restart VtGate, restart VtTablet, restart mysqlD), sometimes the client will grpc.StatusException: CANCELLED.  Currently we are not treating Cancelled StatusException as retriable which caused the Kafka Connect shuts down the connector eventually.

This error should be retriable.

The fix is relatively straightforward, adding Status.CANCELLED as one of the retrieable error.

The exception you can get are something like below:

2022-08-09 22:54:32,085 INFO  || [Consumer clientId=consumer-1-3, groupId=1] Discovered group coordinator slogs-c-kafka-dev-iad-b771.nebula.tinyspeck.com:9092 (id: 2147482636 rack: null)  [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2022-08-09 22:57:14,000 INFO  Vitess|dev|streaming VStream streaming onError. Status: Status{code=CANCELLED, description=target: byuser.-4000.master: vttablet: rpc error: code = Canceled desc = grpc: the client connection is closing, cause=null}  [io.debezium.connector.vitess.connection.VitessReplicationConnection]
io.grpc.StatusRuntimeException: CANCELLED: target: byuser.-4000.master: vttablet: rpc error: code = Canceled desc = grpc: the client connection is closing
    at io.grpc.Status.asRuntimeException(Status.java:533)
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
    at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
    at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
    at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:616)
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:802)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:781)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)

2022-08-09 22:57:19,404 INFO  || Stopping down connector  [io.debezium.connector.common.BaseSourceTask]