DBZ-5551: Refine the Status.CANCELLED retriable handling to only 'client connection is closing' error
The previous commit treats all Status.CANCELLED as retriable error, but it seems there are more places in grpc code which throws Status.CANCELLED.

For example, the below unhandled RuntimeException during StreamObserver.onNext() will be wrapped as Status.CANCELLED and invoke StreamObserver.onError() next.

Since we are only interested in capturing the Status.CANCELLED with regarding to rpc error, constrain the retriable message handling to only 'client connection is closed':

    Status: Status{code=CANCELLED, description=target: byuser.-4000.master: vttablet: rpc error: code = Canceled desc = grpc: the client connection is closing, cause=null}

Also fixed the sequence of that integartion test to execute the illegal DDL (alter table xxx add column @1) after the connector is started so we can capture the parsing error reliably.

Also add the wait time for docker container to 240 seconds, 120 seconds is not enough on my laptop.

Make sure we terminate each CASE statement properly in VitessErrorHandler

Unhandled RuntimeException during onNext() call:

2022-08-24 10:04:30,318 INFO   ||  VStream streaming onError. Status: Status{code=CANCELLED, description=Failed to read message., cause=java.lang.IllegalArgumentException: Illegal prefix '@' for column: @1, from schema: test_unsharded_keyspace, table: numeric_table
	at io.debezium.connector.vitess.connection.VStreamOutputMessageDecoder.validateColumnName(VStreamOutputMessageDecoder.java:431)
	at io.debezium.connector.vitess.connection.VStreamOutputMessageDecoder.handleFieldMessage(VStreamOutputMessageDecoder.java:344)
	at io.debezium.connector.vitess.connection.VStreamOutputMessageDecoder.processMessage(VStreamOutputMessageDecoder.java:69)
	at io.debezium.connector.vitess.connection.VitessReplicationConnection$1.onNext(VitessReplicationConnection.java:189)
	at io.debezium.connector.vitess.connection.VitessReplicationConnection$1.onNext(VitessReplicationConnection.java:94)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:465)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onMessage(DelayedClientCall.java:447)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:715)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:700)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
}   [io.debezium.connector.vitess.connection.VitessReplicationConnection]
io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:616)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:802)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:781)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Illegal prefix '@' for column: @1, from schema: test_unsharded_keyspace, table: numeric_table
	at io.debezium.connector.vitess.connection.VStreamOutputMessageDecoder.validateColumnName(VStreamOutputMessageDecoder.java:431)
	at io.debezium.connector.vitess.connection.VStreamOutputMessageDecoder.handleFieldMessage(VStreamOutputMessageDecoder.java:344)
	at io.debezium.connector.vitess.connection.VStreamOutputMessageDecoder.processMessage(VStreamOutputMessageDecoder.java:69)
	at io.debezium.connector.vitess.connection.VitessReplicationConnection$1.onNext(VitessReplicationConnection.java:189)
	at io.debezium.connector.vitess.connection.VitessReplicationConnection$1.onNext(VitessReplicationConnection.java:94)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:465)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onMessage(DelayedClientCall.java:447)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:715)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:700)